student_name<-c("John","Robert","Priya")
age<-c(18,19,21)
weight<-c(45,35,60)
height<-c(190,142,152)
gender<-c("FEMALE","FEMALE","MALE")
df<-data.frame(student_name,age,weight,height,gender)
df
df$gender=ifelse(df$gender=="MALE","FEMALE","MALE")
df
working_status<-c("yes","no","yes")
df1<-data.frame(row.names=student_name,working_status)
df1
data<-cbind(df1,df)
data
